fixed output path bug

diff --git a/PRJEB8754/analysis/ffpe_artifact_filtering/sobdetector.sh.template b/PRJEB8754/analysis/ffpe_artifact_filtering/sobdetector.sh.template
--- a/PRJEB8754/analysis/ffpe_artifact_filtering/sobdetector.sh.template
+++ b/PRJEB8754/analysis/ffpe_artifact_filtering/sobdetector.sh.template
@@ -2,35 +2,39 @@
 
 set -euo pipefail
 
-bam_fname=$1
-vcf_fname=$2
-sample_name=${vcf_fname%%.*}
+bam_path=$1
+vcf_path=$2
+root_outdir=$3
 
-ref=../../../data/ref/Homo_sapiens_assembly38.fasta
+vcf_name=$(basename $vcf_path)
+sample_name=${vcf_name%%.*}
 
-vcf_indir=../../../data/vcf_ad_filtered
-bam_indir=../../../data/bam
-outdir="../../../ffpe-snvf/sobdetector/$sample_name"
+ref=../../data/ref/Homo_sapiens_assembly38.fasta
 
+# vcf_indir=../../../data/vcf_ad_filtered
+# bam_indir=../../../data/bam
+outdir="${root_outdir}/sobdetector/${sample_name}"
 mkdir -p $outdir
 
 jar="../../../java/SOBDetector_v1.0.4.jar"
 echo $jar
 
-bam=$(echo -n ${bam_indir}/${bam_fname})
+# bam=$(echo -n ${bam_indir}/${bam_path})
+bam=$(echo -n ${bam_path})
 if [[ ! -f $bam ]]; then
-	echo "${bam_indir}/${bam_fname} not found" >&2
+	echo "${bam_path} not found" >&2
 	exit 2
 fi
 
-vcf=$(echo -n ${vcf_indir}/${sample_name}/${vcf_fname})
+vcf=$(echo -n ${vcf_path})
 if [[ ! -f $vcf ]]; then
-	vcf=$(echo -n ${vcf_indir}/${sample_name}/${vcf_fname}.gz)
-	if [[ ! -f $vcf ]]; then
-		echo "${vcf_indir}/${sample_name}/${vcf_fname} not found." >&2
-		exit 2
-	fi
+	echo "${vcf_path} not found." >&2
+	exit 2
 fi
+
+echo "inputs:" >&2
+echo "  $bam" >&2
+echo "  $vcf" >&2
 
 ## Convert VCF to tabular format: ( CHR | POS | REF | ALT ) . As SOBDetector did not work with the VCFs
 snv=${outdir}/${sample_name}.input.snv
diff --git a/PRJEB8754/analysis/ffpe_artifact_filtering/vafsnvf.sh.template b/PRJEB8754/analysis/ffpe_artifact_filtering/vafsnvf.sh.template
--- a/PRJEB8754/analysis/ffpe_artifact_filtering/vafsnvf.sh.template
+++ b/PRJEB8754/analysis/ffpe_artifact_filtering/vafsnvf.sh.template
@@ -4,29 +4,30 @@ set -euo pipefail
 
 bam_fname=$1
 vcf_fname=$2
-sample_name=${vcf_fname%%.*}
+root_outdir=$3
 
-ref=../../../data/ref/Homo_sapiens_assembly38.fasta
+vcf_name=$(basename $vcf_fname)
+sample_name=${vcf_name%%.*}
 
-vcf_indir=../../../data/vcf_ad_filtered
-bam_indir=../../../data/bam
-outdir="../../../ffpe-snvf/vafsnvf/$sample_name"
+ref=../../data/ref/Homo_sapiens_assembly38.fasta
 
+# vcf_indir=../../../data/vcf_ad_filtered
+# bam_indir=../../../data/bam
+outdir="${root_outdir}/vafsnvf/${sample_name}"
 mkdir -p $outdir
 
-bam=$(echo -n ${bam_indir}/${bam_fname})
+
+# bam=$(echo -n ${bam_indir}/${bam_fname})
+bam=$(echo -n ${bam_fname})
 if [[ ! -f $bam ]]; then
-	echo "${bam_indir}/${bam_fname} not found" >&2
+	echo "${bam_fname} not found" >&2
 	exit 2
 fi
 
-vcf=$(echo -n ${vcf_indir}/${sample_name}/${vcf_fname})
+vcf=$(echo -n ${vcf_fname})
 if [[ ! -f $vcf ]]; then
-	vcf=$(echo -n ${vcf_indir}/${sample_name}/${vcf_fname}.gz)
-	if [[ ! -f $vcf ]]; then
-		echo "${vcf_indir}/${sample_name}/${vcf_fname} not found." >&2
-		exit 2
-	fi
+	echo "${vcf_fname} not found." >&2
+	exit 2
 fi
 
 echo "inputs:" >&2
@@ -36,4 +37,4 @@ echo "  $vcf" >&2
 hts-vafsnvf C T $bam $vcf $outdir/${sample_name}.vafsnvf.snv
 
 echo "Finished FFPE SNVF Filtering"
-echo -e "\tOutput saved to: $outdir/${sample_name}.mobsnvf.snv"
+echo -e "\tOutput saved to: $outdir/${sample_name}.vafsnvf.snv"
